redis:
  image: redis
db:
  image: mariadb:5.5
  environment:
    "MYSQL_ROOT_PASSWORD": "etpass123"
    "MYSQL_DATABASE": "sunshop"
  command: "mysqld --character-set-server=utf8"
  ports:
    - "127.0.0.1:3306:3306"
  volumes:
    - "/node/sunshop/db:/var/lib/mysql"
web:
  image: wizzer/sunshop
  links:
    - redis
    - db
  environment:
    "MYSQL_HOST": "db"
    "MYSQL_USER": "root"
    "MYSQL_PASSWORD": "etpass123"
    "MYSQL_DATABASE": "sunshop"
    "MYSQL_LIMIT": 150
    "REDIS_HOST": "redis"
    "REDIS_PASS": ""
    "LOG_LEVEL": "verbose"
    "LOG_SQL": "false"
    "PORT": 1337
    "NODE_ENV": "production"
  command: "pm2 start /node/sunshop/app.js --no-daemon"
  ports:
    - "1337:1337"
  volumes:
    - "/node/sunshop/cert:/node/sunshop/cert"
    - "/node/sunshop/upload:/node/sunshop/upload"
    - "/node/sunshop/backup:/node/sunshop/backup"
